sudo: false
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
script:
- |
  cargo build &&
  cargo test &&
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
notifications:
  email:
    on_success: never
env:
  global:
  - secure: # encrypted stuff